# $Header: /CVSROOT/scylla-charybdis/example/Makefile,v 1.1 2003/11/06 12:09:06 tino Exp $
#
# $Log: Makefile,v $
# Revision 1.1  2003/11/06 12:09:06  tino
# added
#

CFLAGS=-Wall -O2

APPS=read-nonblocking

all:	$(APPS)

clean:
	$(RM) $(APPS)

distclean:	clean
	$(RM) *~
